package com.springboot.college.mapper;

import com.springboot.college.model.ImgsInfo;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

@Mapper
@Component("ImgsInfoMapper")
public interface ImgsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs_info
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from imgs_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs_info
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into imgs_info (id, name, ",
        "sysName, imgType, ",
        "imgSize, imgPath, ",
        "directoryId, tag, ",
        "imgPathType, REMARK, ",
        "CREATER, CREATE_TIME, ",
        "MODIFIER, MODIFY_TIME, ",
        "DISABLED, VERSION)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{sysname,jdbcType=VARCHAR}, #{imgtype,jdbcType=VARCHAR}, ",
        "#{imgsize,jdbcType=VARCHAR}, #{imgpath,jdbcType=VARCHAR}, ",
        "#{directoryid,jdbcType=VARCHAR}, #{tag,jdbcType=INTEGER}, ",
        "#{imgpathtype,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{creater,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifier,jdbcType=VARCHAR}, #{modifyTime,jdbcType=TIMESTAMP}, ",
        "#{disabled,jdbcType=VARCHAR}, #{version,jdbcType=VARCHAR})"
    })
    int insert(ImgsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs_info
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(ImgsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs_info
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs_info
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(ImgsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs_info
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update imgs_info",
        "set name = #{name,jdbcType=VARCHAR},",
          "sysName = #{sysname,jdbcType=VARCHAR},",
          "imgType = #{imgtype,jdbcType=VARCHAR},",
          "imgSize = #{imgsize,jdbcType=VARCHAR},",
          "imgPath = #{imgpath,jdbcType=VARCHAR},",
          "directoryId = #{directoryid,jdbcType=VARCHAR},",
          "tag = #{tag,jdbcType=INTEGER},",
          "imgPathType = #{imgpathtype,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "CREATER = #{creater,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "MODIFIER = #{modifier,jdbcType=VARCHAR},",
          "MODIFY_TIME = #{modifyTime,jdbcType=TIMESTAMP},",
          "DISABLED = #{disabled,jdbcType=VARCHAR},",
          "VERSION = #{version,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ImgsInfo record);

    int save(ImgsInfo imgsInfo);
}