package com.springboot.college.mapper;

import com.springboot.college.model.JshAccountItem;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshAccountItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accountitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_accountitem",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accountitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_accountitem (Id, HeaderId, ",
        "AccountId, InOutItemId, ",
        "EachAmount, Remark, ",
        "tenant_id, delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{headerid,jdbcType=BIGINT}, ",
        "#{accountid,jdbcType=BIGINT}, #{inoutitemid,jdbcType=BIGINT}, ",
        "#{eachamount,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshAccountItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accountitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshAccountItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accountitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accountitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshAccountItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accountitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_accountitem",
        "set HeaderId = #{headerid,jdbcType=BIGINT},",
          "AccountId = #{accountid,jdbcType=BIGINT},",
          "InOutItemId = #{inoutitemid,jdbcType=BIGINT},",
          "EachAmount = #{eachamount,jdbcType=DECIMAL},",
          "Remark = #{remark,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshAccountItem record);
}