package com.springboot.college.mapper;

import com.springboot.college.model.JshAccountHead;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshAccountHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_accounthead",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_accounthead (Id, Type, ",
        "OrganId, HandsPersonId, ",
        "ChangeAmount, TotalPrice, ",
        "AccountId, BillNo, ",
        "BillTime, Remark, ",
        "tenant_id, delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=VARCHAR}, ",
        "#{organid,jdbcType=BIGINT}, #{handspersonid,jdbcType=BIGINT}, ",
        "#{changeamount,jdbcType=DECIMAL}, #{totalprice,jdbcType=DECIMAL}, ",
        "#{accountid,jdbcType=BIGINT}, #{billno,jdbcType=VARCHAR}, ",
        "#{billtime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshAccountHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshAccountHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshAccountHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_accounthead",
        "set Type = #{type,jdbcType=VARCHAR},",
          "OrganId = #{organid,jdbcType=BIGINT},",
          "HandsPersonId = #{handspersonid,jdbcType=BIGINT},",
          "ChangeAmount = #{changeamount,jdbcType=DECIMAL},",
          "TotalPrice = #{totalprice,jdbcType=DECIMAL},",
          "AccountId = #{accountid,jdbcType=BIGINT},",
          "BillNo = #{billno,jdbcType=VARCHAR},",
          "BillTime = #{billtime,jdbcType=TIMESTAMP},",
          "Remark = #{remark,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshAccountHead record);
}