package com.springboot.college.mapper;

import com.springboot.college.model.JshAccount;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_account
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_account",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_account
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_account (Id, Name, ",
        "SerialNo, InitialAmount, ",
        "CurrentAmount, Remark, ",
        "IsDefault, tenant_id, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{serialno,jdbcType=VARCHAR}, #{initialamount,jdbcType=DECIMAL}, ",
        "#{currentamount,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, ",
        "#{isdefault,jdbcType=BIT}, #{tenantId,jdbcType=BIGINT}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_account
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_account
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_account
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_account
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_account",
        "set Name = #{name,jdbcType=VARCHAR},",
          "SerialNo = #{serialno,jdbcType=VARCHAR},",
          "InitialAmount = #{initialamount,jdbcType=DECIMAL},",
          "CurrentAmount = #{currentamount,jdbcType=DECIMAL},",
          "Remark = #{remark,jdbcType=VARCHAR},",
          "IsDefault = #{isdefault,jdbcType=BIT},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshAccount record);
}