package com.springboot.college.mapper;

import com.springboot.college.model.JshDepot;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshDepotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_depot",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_depot (id, name, ",
        "address, warehousing, ",
        "truckage, type, ",
        "sort, remark, principal, ",
        "tenant_id, delete_Flag, ",
        "is_default)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{warehousing,jdbcType=DECIMAL}, ",
        "#{truckage,jdbcType=DECIMAL}, #{type,jdbcType=INTEGER}, ",
        "#{sort,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, #{principal,jdbcType=BIGINT}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFlag,jdbcType=VARCHAR}, ",
        "#{isDefault,jdbcType=BIT})"
    })
    int insert(JshDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_depot",
        "set name = #{name,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "warehousing = #{warehousing,jdbcType=DECIMAL},",
          "truckage = #{truckage,jdbcType=DECIMAL},",
          "type = #{type,jdbcType=INTEGER},",
          "sort = #{sort,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "principal = #{principal,jdbcType=BIGINT},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR},",
          "is_default = #{isDefault,jdbcType=BIT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshDepot record);
}