package com.springboot.college.mapper;

import com.springboot.college.model.JshDepotHead;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshDepotHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_depothead",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_depothead (Id, Type, ",
        "SubType, DefaultNumber, ",
        "Number, OperPersonName, ",
        "CreateTime, OperTime, ",
        "OrganId, HandsPersonId, ",
        "AccountId, ChangeAmount, ",
        "TotalPrice, PayType, ",
        "Remark, Salesman, ",
        "AccountIdList, AccountMoneyList, ",
        "Discount, DiscountMoney, ",
        "DiscountLastMoney, OtherMoney, ",
        "OtherMoneyList, OtherMoneyItem, ",
        "AccountDay, Status, ",
        "LinkNumber, tenant_id, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=VARCHAR}, ",
        "#{subtype,jdbcType=VARCHAR}, #{defaultnumber,jdbcType=VARCHAR}, ",
        "#{number,jdbcType=VARCHAR}, #{operpersonname,jdbcType=VARCHAR}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{opertime,jdbcType=TIMESTAMP}, ",
        "#{organid,jdbcType=BIGINT}, #{handspersonid,jdbcType=BIGINT}, ",
        "#{accountid,jdbcType=BIGINT}, #{changeamount,jdbcType=DECIMAL}, ",
        "#{totalprice,jdbcType=DECIMAL}, #{paytype,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{salesman,jdbcType=VARCHAR}, ",
        "#{accountidlist,jdbcType=VARCHAR}, #{accountmoneylist,jdbcType=VARCHAR}, ",
        "#{discount,jdbcType=DECIMAL}, #{discountmoney,jdbcType=DECIMAL}, ",
        "#{discountlastmoney,jdbcType=DECIMAL}, #{othermoney,jdbcType=DECIMAL}, ",
        "#{othermoneylist,jdbcType=VARCHAR}, #{othermoneyitem,jdbcType=VARCHAR}, ",
        "#{accountday,jdbcType=INTEGER}, #{status,jdbcType=VARCHAR}, ",
        "#{linknumber,jdbcType=VARCHAR}, #{tenantId,jdbcType=BIGINT}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshDepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshDepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshDepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depothead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_depothead",
        "set Type = #{type,jdbcType=VARCHAR},",
          "SubType = #{subtype,jdbcType=VARCHAR},",
          "DefaultNumber = #{defaultnumber,jdbcType=VARCHAR},",
          "Number = #{number,jdbcType=VARCHAR},",
          "OperPersonName = #{operpersonname,jdbcType=VARCHAR},",
          "CreateTime = #{createtime,jdbcType=TIMESTAMP},",
          "OperTime = #{opertime,jdbcType=TIMESTAMP},",
          "OrganId = #{organid,jdbcType=BIGINT},",
          "HandsPersonId = #{handspersonid,jdbcType=BIGINT},",
          "AccountId = #{accountid,jdbcType=BIGINT},",
          "ChangeAmount = #{changeamount,jdbcType=DECIMAL},",
          "TotalPrice = #{totalprice,jdbcType=DECIMAL},",
          "PayType = #{paytype,jdbcType=VARCHAR},",
          "Remark = #{remark,jdbcType=VARCHAR},",
          "Salesman = #{salesman,jdbcType=VARCHAR},",
          "AccountIdList = #{accountidlist,jdbcType=VARCHAR},",
          "AccountMoneyList = #{accountmoneylist,jdbcType=VARCHAR},",
          "Discount = #{discount,jdbcType=DECIMAL},",
          "DiscountMoney = #{discountmoney,jdbcType=DECIMAL},",
          "DiscountLastMoney = #{discountlastmoney,jdbcType=DECIMAL},",
          "OtherMoney = #{othermoney,jdbcType=DECIMAL},",
          "OtherMoneyList = #{othermoneylist,jdbcType=VARCHAR},",
          "OtherMoneyItem = #{othermoneyitem,jdbcType=VARCHAR},",
          "AccountDay = #{accountday,jdbcType=INTEGER},",
          "Status = #{status,jdbcType=VARCHAR},",
          "LinkNumber = #{linknumber,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshDepotHead record);
}