package com.springboot.college.mapper;

import com.springboot.college.model.JshFunctions;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshFunctionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_functions",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_functions (Id, Number, ",
        "Name, PNumber, URL, ",
        "State, Sort, Enabled, ",
        "Type, PushBtn, icon, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{number,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{pnumber,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=BIT}, #{sort,jdbcType=VARCHAR}, #{enabled,jdbcType=BIT}, ",
        "#{type,jdbcType=VARCHAR}, #{pushbtn,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshFunctions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshFunctions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshFunctions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_functions",
        "set Number = #{number,jdbcType=VARCHAR},",
          "Name = #{name,jdbcType=VARCHAR},",
          "PNumber = #{pnumber,jdbcType=VARCHAR},",
          "URL = #{url,jdbcType=VARCHAR},",
          "State = #{state,jdbcType=BIT},",
          "Sort = #{sort,jdbcType=VARCHAR},",
          "Enabled = #{enabled,jdbcType=BIT},",
          "Type = #{type,jdbcType=VARCHAR},",
          "PushBtn = #{pushbtn,jdbcType=VARCHAR},",
          "icon = #{icon,jdbcType=VARCHAR},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshFunctions record);
}