package com.springboot.college.mapper;

import com.springboot.college.model.JshInoutItem;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshInoutItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_inoutitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_inoutitem",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_inoutitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_inoutitem (Id, Name, ",
        "Type, Remark, tenant_id, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, #{tenantId,jdbcType=BIGINT}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshInoutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_inoutitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshInoutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_inoutitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_inoutitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshInoutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_inoutitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_inoutitem",
        "set Name = #{name,jdbcType=VARCHAR},",
          "Type = #{type,jdbcType=VARCHAR},",
          "Remark = #{remark,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshInoutItem record);
}