package com.springboot.college.mapper;

import com.springboot.college.model.JshMaterialStock;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshMaterialStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_stock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_material_stock",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_stock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_material_stock (id, material_id, ",
        "depot_id, number, ",
        "tenant_id, delete_fag)",
        "values (#{id,jdbcType=BIGINT}, #{materialId,jdbcType=BIGINT}, ",
        "#{depotId,jdbcType=BIGINT}, #{number,jdbcType=DECIMAL}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFag,jdbcType=VARCHAR})"
    })
    int insert(JshMaterialStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_stock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshMaterialStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_stock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_stock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshMaterialStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_stock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_material_stock",
        "set material_id = #{materialId,jdbcType=BIGINT},",
          "depot_id = #{depotId,jdbcType=BIGINT},",
          "number = #{number,jdbcType=DECIMAL},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_fag = #{deleteFag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshMaterialStock record);
}