package com.springboot.college.mapper;

import com.springboot.college.model.JshMaterialCategory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshMaterialCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_materialcategory",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_materialcategory (Id, Name, ",
        "CategoryLevel, ParentId, ",
        "sort, status, serial_no, ",
        "remark, create_time, ",
        "creator, update_time, ",
        "updater, tenant_id)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{categorylevel,jdbcType=SMALLINT}, #{parentid,jdbcType=BIGINT}, ",
        "#{sort,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{serialNo,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=BIGINT}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updater,jdbcType=BIGINT}, #{tenantId,jdbcType=BIGINT})"
    })
    int insert(JshMaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshMaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshMaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_materialcategory",
        "set Name = #{name,jdbcType=VARCHAR},",
          "CategoryLevel = #{categorylevel,jdbcType=SMALLINT},",
          "ParentId = #{parentid,jdbcType=BIGINT},",
          "sort = #{sort,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "serial_no = #{serialNo,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=BIGINT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "updater = #{updater,jdbcType=BIGINT},",
          "tenant_id = #{tenantId,jdbcType=BIGINT}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshMaterialCategory record);
}