package com.springboot.college.mapper;

import com.springboot.college.model.JshMaterialExtend;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshMaterialExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_extend
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_material_extend",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_extend
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_material_extend (id, material_id, ",
        "bar_code, commodity_unit, ",
        "purchase_decimal, commodity_decimal, ",
        "wholesale_decimal, low_decimal, ",
        "create_time, create_serial, ",
        "update_serial, update_time, ",
        "tenant_id, delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{materialId,jdbcType=BIGINT}, ",
        "#{barCode,jdbcType=VARCHAR}, #{commodityUnit,jdbcType=VARCHAR}, ",
        "#{purchaseDecimal,jdbcType=DECIMAL}, #{commodityDecimal,jdbcType=DECIMAL}, ",
        "#{wholesaleDecimal,jdbcType=DECIMAL}, #{lowDecimal,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createSerial,jdbcType=VARCHAR}, ",
        "#{updateSerial,jdbcType=VARCHAR}, #{updateTime,jdbcType=BIGINT}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshMaterialExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_extend
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshMaterialExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_extend
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_extend
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshMaterialExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material_extend
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_material_extend",
        "set material_id = #{materialId,jdbcType=BIGINT},",
          "bar_code = #{barCode,jdbcType=VARCHAR},",
          "commodity_unit = #{commodityUnit,jdbcType=VARCHAR},",
          "purchase_decimal = #{purchaseDecimal,jdbcType=DECIMAL},",
          "commodity_decimal = #{commodityDecimal,jdbcType=DECIMAL},",
          "wholesale_decimal = #{wholesaleDecimal,jdbcType=DECIMAL},",
          "low_decimal = #{lowDecimal,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_serial = #{createSerial,jdbcType=VARCHAR},",
          "update_serial = #{updateSerial,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=BIGINT},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshMaterialExtend record);
}