package com.springboot.college.mapper;

import com.springboot.college.model.JshMsg;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_msg",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_msg (id, msg_title, ",
        "msg_content, create_time, ",
        "type, status, tenant_id, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{msgTitle,jdbcType=VARCHAR}, ",
        "#{msgContent,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{type,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{tenantId,jdbcType=BIGINT}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_msg",
        "set msg_title = #{msgTitle,jdbcType=VARCHAR},",
          "msg_content = #{msgContent,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "type = #{type,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshMsg record);
}