package com.springboot.college.mapper;

import com.springboot.college.model.JshMaterialProperty;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshMaterialPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_materialproperty",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_materialproperty (id, nativeName, ",
        "enabled, sort, anotherName, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{nativename,jdbcType=VARCHAR}, ",
        "#{enabled,jdbcType=BIT}, #{sort,jdbcType=VARCHAR}, #{anothername,jdbcType=VARCHAR}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshMaterialProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshMaterialProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshMaterialProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_materialproperty",
        "set nativeName = #{nativename,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=BIT},",
          "sort = #{sort,jdbcType=VARCHAR},",
          "anotherName = #{anothername,jdbcType=VARCHAR},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshMaterialProperty record);
}