package com.springboot.college.mapper;

import com.springboot.college.model.JshOrganization;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_organization",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_organization (id, org_no, ",
        "org_full_name, org_abr, ",
        "org_tpcd, org_stcd, org_parent_no, ",
        "sort, remark, create_time, ",
        "creator, update_time, ",
        "updater, org_create_time, ",
        "org_stop_time, tenant_id)",
        "values (#{id,jdbcType=BIGINT}, #{orgNo,jdbcType=VARCHAR}, ",
        "#{orgFullName,jdbcType=VARCHAR}, #{orgAbr,jdbcType=VARCHAR}, ",
        "#{orgTpcd,jdbcType=VARCHAR}, #{orgStcd,jdbcType=CHAR}, #{orgParentNo,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=BIGINT}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updater,jdbcType=BIGINT}, #{orgCreateTime,jdbcType=TIMESTAMP}, ",
        "#{orgStopTime,jdbcType=TIMESTAMP}, #{tenantId,jdbcType=BIGINT})"
    })
    int insert(JshOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_organization
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_organization",
        "set org_no = #{orgNo,jdbcType=VARCHAR},",
          "org_full_name = #{orgFullName,jdbcType=VARCHAR},",
          "org_abr = #{orgAbr,jdbcType=VARCHAR},",
          "org_tpcd = #{orgTpcd,jdbcType=VARCHAR},",
          "org_stcd = #{orgStcd,jdbcType=CHAR},",
          "org_parent_no = #{orgParentNo,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=BIGINT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "updater = #{updater,jdbcType=BIGINT},",
          "org_create_time = #{orgCreateTime,jdbcType=TIMESTAMP},",
          "org_stop_time = #{orgStopTime,jdbcType=TIMESTAMP},",
          "tenant_id = #{tenantId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshOrganization record);
}