package com.springboot.college.mapper;

import com.springboot.college.model.JshOrgaUserRel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshOrgaUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_orga_user_rel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_orga_user_rel (id, orga_id, ",
        "user_id, user_blng_orga_dspl_seq, ",
        "delete_flag, create_time, ",
        "creator, update_time, ",
        "updater, tenant_id)",
        "values (#{id,jdbcType=BIGINT}, #{orgaId,jdbcType=BIGINT}, ",
        "#{userId,jdbcType=BIGINT}, #{userBlngOrgaDsplSeq,jdbcType=VARCHAR}, ",
        "#{deleteFlag,jdbcType=CHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=BIGINT}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updater,jdbcType=BIGINT}, #{tenantId,jdbcType=BIGINT})"
    })
    int insert(JshOrgaUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshOrgaUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshOrgaUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_orga_user_rel",
        "set orga_id = #{orgaId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "user_blng_orga_dspl_seq = #{userBlngOrgaDsplSeq,jdbcType=VARCHAR},",
          "delete_flag = #{deleteFlag,jdbcType=CHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=BIGINT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "updater = #{updater,jdbcType=BIGINT},",
          "tenant_id = #{tenantId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshOrgaUserRel record);
}