package com.springboot.college.mapper;

import com.springboot.college.model.JshSupplier;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_supplier
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_supplier",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_supplier
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_supplier (id, supplier, ",
        "contacts, phonenum, ",
        "email, description, ",
        "isystem, type, enabled, ",
        "AdvanceIn, BeginNeedGet, ",
        "BeginNeedPay, AllNeedGet, ",
        "AllNeedPay, fax, ",
        "telephone, address, ",
        "taxNum, bankName, ",
        "accountNumber, taxRate, ",
        "tenant_id, delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{supplier,jdbcType=VARCHAR}, ",
        "#{contacts,jdbcType=VARCHAR}, #{phonenum,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{isystem,jdbcType=TINYINT}, #{type,jdbcType=VARCHAR}, #{enabled,jdbcType=BIT}, ",
        "#{advancein,jdbcType=DECIMAL}, #{beginneedget,jdbcType=DECIMAL}, ",
        "#{beginneedpay,jdbcType=DECIMAL}, #{allneedget,jdbcType=DECIMAL}, ",
        "#{allneedpay,jdbcType=DECIMAL}, #{fax,jdbcType=VARCHAR}, ",
        "#{telephone,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{taxnum,jdbcType=VARCHAR}, #{bankname,jdbcType=VARCHAR}, ",
        "#{accountnumber,jdbcType=VARCHAR}, #{taxrate,jdbcType=DECIMAL}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_supplier
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_supplier
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_supplier
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_supplier
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_supplier",
        "set supplier = #{supplier,jdbcType=VARCHAR},",
          "contacts = #{contacts,jdbcType=VARCHAR},",
          "phonenum = #{phonenum,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "isystem = #{isystem,jdbcType=TINYINT},",
          "type = #{type,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=BIT},",
          "AdvanceIn = #{advancein,jdbcType=DECIMAL},",
          "BeginNeedGet = #{beginneedget,jdbcType=DECIMAL},",
          "BeginNeedPay = #{beginneedpay,jdbcType=DECIMAL},",
          "AllNeedGet = #{allneedget,jdbcType=DECIMAL},",
          "AllNeedPay = #{allneedpay,jdbcType=DECIMAL},",
          "fax = #{fax,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "taxNum = #{taxnum,jdbcType=VARCHAR},",
          "bankName = #{bankname,jdbcType=VARCHAR},",
          "accountNumber = #{accountnumber,jdbcType=VARCHAR},",
          "taxRate = #{taxrate,jdbcType=DECIMAL},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshSupplier record);
}