package com.springboot.college.mapper;

import com.springboot.college.model.JshSystemConfig;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshSystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_systemconfig",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_systemconfig (id, company_name, ",
        "company_contacts, company_address, ",
        "company_tel, company_fax, ",
        "company_post_code, depot_flag, ",
        "customer_flag, tenant_id, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{companyName,jdbcType=VARCHAR}, ",
        "#{companyContacts,jdbcType=VARCHAR}, #{companyAddress,jdbcType=VARCHAR}, ",
        "#{companyTel,jdbcType=VARCHAR}, #{companyFax,jdbcType=VARCHAR}, ",
        "#{companyPostCode,jdbcType=VARCHAR}, #{depotFlag,jdbcType=VARCHAR}, ",
        "#{customerFlag,jdbcType=VARCHAR}, #{tenantId,jdbcType=BIGINT}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_systemconfig",
        "set company_name = #{companyName,jdbcType=VARCHAR},",
          "company_contacts = #{companyContacts,jdbcType=VARCHAR},",
          "company_address = #{companyAddress,jdbcType=VARCHAR},",
          "company_tel = #{companyTel,jdbcType=VARCHAR},",
          "company_fax = #{companyFax,jdbcType=VARCHAR},",
          "company_post_code = #{companyPostCode,jdbcType=VARCHAR},",
          "depot_flag = #{depotFlag,jdbcType=VARCHAR},",
          "customer_flag = #{customerFlag,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshSystemConfig record);
}