package com.springboot.college.mapper;

import com.springboot.college.model.JshTenant;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshTenantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_tenant",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_tenant (id, tenant_id, ",
        "login_name, user_num_limit, ",
        "bills_num_limit, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{tenantId,jdbcType=BIGINT}, ",
        "#{loginName,jdbcType=VARCHAR}, #{userNumLimit,jdbcType=INTEGER}, ",
        "#{billsNumLimit,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(JshTenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshTenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshTenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_tenant",
        "set tenant_id = #{tenantId,jdbcType=BIGINT},",
          "login_name = #{loginName,jdbcType=VARCHAR},",
          "user_num_limit = #{userNumLimit,jdbcType=INTEGER},",
          "bills_num_limit = #{billsNumLimit,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshTenant record);
}