package com.springboot.college.mapper;

import com.springboot.college.model.JshUnit;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_unit",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_unit (id, UName, ",
        "tenant_id, delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{uname,jdbcType=VARCHAR}, ",
        "#{tenantId,jdbcType=BIGINT}, #{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_unit",
        "set UName = #{uname,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshUnit record);
}