package com.springboot.college.mapper;

import com.springboot.college.model.JshUserBusiness;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;

public interface JshUserBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_userbusiness",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_userbusiness (Id, Type, ",
        "KeyId, Value, BtnStr, ",
        "delete_Flag)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=VARCHAR}, ",
        "#{keyid,jdbcType=VARCHAR}, #{value,jdbcType=VARCHAR}, #{btnstr,jdbcType=VARCHAR}, ",
        "#{deleteFlag,jdbcType=VARCHAR})"
    })
    int insert(JshUserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshUserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshUserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_userbusiness",
        "set Type = #{type,jdbcType=VARCHAR},",
          "KeyId = #{keyid,jdbcType=VARCHAR},",
          "Value = #{value,jdbcType=VARCHAR},",
          "BtnStr = #{btnstr,jdbcType=VARCHAR},",
          "delete_Flag = #{deleteFlag,jdbcType=VARCHAR}",
        "where Id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshUserBusiness record);
}