package com.springboot.college.mapper;

import com.springboot.college.model.JshUser;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.Map;

@Mapper
@Component("JshUserMapper")
public interface JshUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Delete({
        "delete from jsh_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Insert({
        "insert into jsh_user (id, username, ",
        "loginame, password, ",
        "position, department, ",
        "email, phonenum, ",
        "ismanager, isystem, ",
        "Status, description, ",
        "remark, tenant_id)",
        "values (#{id,jdbcType=BIGINT}, #{username,jdbcType=VARCHAR}, ",
        "#{loginame,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{position,jdbcType=VARCHAR}, #{department,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{phonenum,jdbcType=VARCHAR}, ",
        "#{ismanager,jdbcType=TINYINT}, #{isystem,jdbcType=TINYINT}, ",
        "#{status,jdbcType=TINYINT}, #{description,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{tenantId,jdbcType=BIGINT})"
    })
    int insert(JshUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int insertSelective(JshUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    int updateByPrimaryKeySelective(JshUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Update({
        "update jsh_user",
        "set username = #{username,jdbcType=VARCHAR},",
          "loginame = #{loginame,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "position = #{position,jdbcType=VARCHAR},",
          "department = #{department,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "phonenum = #{phonenum,jdbcType=VARCHAR},",
          "ismanager = #{ismanager,jdbcType=TINYINT},",
          "isystem = #{isystem,jdbcType=TINYINT},",
          "Status = #{status,jdbcType=TINYINT},",
          "description = #{description,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "tenant_id = #{tenantId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(JshUser record);
    Map<String,String> getUser(@Param(value = "username") String username);
}