package com.springboot.college.mapper;

import com.springboot.college.model.SysLog;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

@Mapper
@Component("SysLogMapper")
public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Apr 13 15:06:14 CST 2020
     */
    @Delete({
        "delete from sys_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Apr 13 15:06:14 CST 2020
     */
    @Insert({
        "insert into sys_log (id, username, ",
        "operation, time, ",
        "method, params, ",
        "ip, create_time)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{operation,jdbcType=VARCHAR}, #{time,jdbcType=TIMESTAMP}, ",
        "#{method,jdbcType=VARCHAR}, #{params,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Apr 13 15:06:14 CST 2020
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Apr 13 15:06:14 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Apr 13 15:06:14 CST 2020
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Mon Apr 13 15:06:14 CST 2020
     */
    @Update({
        "update sys_log",
        "set username = #{username,jdbcType=VARCHAR},",
          "operation = #{operation,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "method = #{method,jdbcType=VARCHAR},",
          "params = #{params,jdbcType=VARCHAR},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysLog record);
}