package com.springboot.college.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class JshAccountHead implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.OrganId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long organid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.HandsPersonId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long handspersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.ChangeAmount
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal changeamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.TotalPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.AccountId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.BillNo
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String billno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.BillTime
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date billtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_accounthead.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.Id
     *
     * @return the value of jsh_accounthead.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.Id
     *
     * @param id the value for jsh_accounthead.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.Type
     *
     * @return the value of jsh_accounthead.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.Type
     *
     * @param type the value for jsh_accounthead.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.OrganId
     *
     * @return the value of jsh_accounthead.OrganId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withOrganid(Long organid) {
        this.setOrganid(organid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.OrganId
     *
     * @param organid the value for jsh_accounthead.OrganId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOrganid(Long organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.HandsPersonId
     *
     * @return the value of jsh_accounthead.HandsPersonId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getHandspersonid() {
        return handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withHandspersonid(Long handspersonid) {
        this.setHandspersonid(handspersonid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.HandsPersonId
     *
     * @param handspersonid the value for jsh_accounthead.HandsPersonId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setHandspersonid(Long handspersonid) {
        this.handspersonid = handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.ChangeAmount
     *
     * @return the value of jsh_accounthead.ChangeAmount
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withChangeamount(BigDecimal changeamount) {
        this.setChangeamount(changeamount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.ChangeAmount
     *
     * @param changeamount the value for jsh_accounthead.ChangeAmount
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setChangeamount(BigDecimal changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.TotalPrice
     *
     * @return the value of jsh_accounthead.TotalPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withTotalprice(BigDecimal totalprice) {
        this.setTotalprice(totalprice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.TotalPrice
     *
     * @param totalprice the value for jsh_accounthead.TotalPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.AccountId
     *
     * @return the value of jsh_accounthead.AccountId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withAccountid(Long accountid) {
        this.setAccountid(accountid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.AccountId
     *
     * @param accountid the value for jsh_accounthead.AccountId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.BillNo
     *
     * @return the value of jsh_accounthead.BillNo
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withBillno(String billno) {
        this.setBillno(billno);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.BillNo
     *
     * @param billno the value for jsh_accounthead.BillNo
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.BillTime
     *
     * @return the value of jsh_accounthead.BillTime
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getBilltime() {
        return billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withBilltime(Date billtime) {
        this.setBilltime(billtime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.BillTime
     *
     * @param billtime the value for jsh_accounthead.BillTime
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setBilltime(Date billtime) {
        this.billtime = billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.Remark
     *
     * @return the value of jsh_accounthead.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.Remark
     *
     * @param remark the value for jsh_accounthead.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.tenant_id
     *
     * @return the value of jsh_accounthead.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.tenant_id
     *
     * @param tenantId the value for jsh_accounthead.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_accounthead.delete_Flag
     *
     * @return the value of jsh_accounthead.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshAccountHead withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_accounthead.delete_Flag
     *
     * @param deleteFlag the value for jsh_accounthead.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_accounthead
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", organid=").append(organid);
        sb.append(", handspersonid=").append(handspersonid);
        sb.append(", changeamount=").append(changeamount);
        sb.append(", totalprice=").append(totalprice);
        sb.append(", accountid=").append(accountid);
        sb.append(", billno=").append(billno);
        sb.append(", billtime=").append(billtime);
        sb.append(", remark=").append(remark);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}