package com.springboot.college.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class JshdepotItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.HeaderId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long headerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.MaterialId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long materialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.material_extend_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long materialExtendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.MUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String munit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OperNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal opernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.BasicNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal basicnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.UnitPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal unitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxUnitPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal taxunitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.AllPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Img
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.Incidentals
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal incidentals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.DepotId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long depotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.AnotherDepotId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long anotherdepotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxRate
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal taxrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxMoney
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal taxmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.TaxLastMoney
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal taxlastmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField1
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField2
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField3
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField4
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.OtherField5
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.MType
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String mtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depotitem.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Id
     *
     * @return the value of jsh_depotitem.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Id
     *
     * @param id the value for jsh_depotitem.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.HeaderId
     *
     * @return the value of jsh_depotitem.HeaderId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getHeaderid() {
        return headerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withHeaderid(Long headerid) {
        this.setHeaderid(headerid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.HeaderId
     *
     * @param headerid the value for jsh_depotitem.HeaderId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setHeaderid(Long headerid) {
        this.headerid = headerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.MaterialId
     *
     * @return the value of jsh_depotitem.MaterialId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withMaterialid(Long materialid) {
        this.setMaterialid(materialid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.MaterialId
     *
     * @param materialid the value for jsh_depotitem.MaterialId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMaterialid(Long materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.material_extend_id
     *
     * @return the value of jsh_depotitem.material_extend_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getMaterialExtendId() {
        return materialExtendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withMaterialExtendId(Long materialExtendId) {
        this.setMaterialExtendId(materialExtendId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.material_extend_id
     *
     * @param materialExtendId the value for jsh_depotitem.material_extend_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMaterialExtendId(Long materialExtendId) {
        this.materialExtendId = materialExtendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.MUnit
     *
     * @return the value of jsh_depotitem.MUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getMunit() {
        return munit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withMunit(String munit) {
        this.setMunit(munit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.MUnit
     *
     * @param munit the value for jsh_depotitem.MUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMunit(String munit) {
        this.munit = munit == null ? null : munit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OperNumber
     *
     * @return the value of jsh_depotitem.OperNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getOpernumber() {
        return opernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withOpernumber(BigDecimal opernumber) {
        this.setOpernumber(opernumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OperNumber
     *
     * @param opernumber the value for jsh_depotitem.OperNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOpernumber(BigDecimal opernumber) {
        this.opernumber = opernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.BasicNumber
     *
     * @return the value of jsh_depotitem.BasicNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getBasicnumber() {
        return basicnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withBasicnumber(BigDecimal basicnumber) {
        this.setBasicnumber(basicnumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.BasicNumber
     *
     * @param basicnumber the value for jsh_depotitem.BasicNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setBasicnumber(BigDecimal basicnumber) {
        this.basicnumber = basicnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.UnitPrice
     *
     * @return the value of jsh_depotitem.UnitPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withUnitprice(BigDecimal unitprice) {
        this.setUnitprice(unitprice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.UnitPrice
     *
     * @param unitprice the value for jsh_depotitem.UnitPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxUnitPrice
     *
     * @return the value of jsh_depotitem.TaxUnitPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getTaxunitprice() {
        return taxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withTaxunitprice(BigDecimal taxunitprice) {
        this.setTaxunitprice(taxunitprice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxUnitPrice
     *
     * @param taxunitprice the value for jsh_depotitem.TaxUnitPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTaxunitprice(BigDecimal taxunitprice) {
        this.taxunitprice = taxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.AllPrice
     *
     * @return the value of jsh_depotitem.AllPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withAllprice(BigDecimal allprice) {
        this.setAllprice(allprice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.AllPrice
     *
     * @param allprice the value for jsh_depotitem.AllPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setAllprice(BigDecimal allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Remark
     *
     * @return the value of jsh_depotitem.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Remark
     *
     * @param remark the value for jsh_depotitem.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Img
     *
     * @return the value of jsh_depotitem.Img
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withImg(String img) {
        this.setImg(img);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Img
     *
     * @param img the value for jsh_depotitem.Img
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.Incidentals
     *
     * @return the value of jsh_depotitem.Incidentals
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getIncidentals() {
        return incidentals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withIncidentals(BigDecimal incidentals) {
        this.setIncidentals(incidentals);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.Incidentals
     *
     * @param incidentals the value for jsh_depotitem.Incidentals
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIncidentals(BigDecimal incidentals) {
        this.incidentals = incidentals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.DepotId
     *
     * @return the value of jsh_depotitem.DepotId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getDepotid() {
        return depotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withDepotid(Long depotid) {
        this.setDepotid(depotid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.DepotId
     *
     * @param depotid the value for jsh_depotitem.DepotId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDepotid(Long depotid) {
        this.depotid = depotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.AnotherDepotId
     *
     * @return the value of jsh_depotitem.AnotherDepotId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getAnotherdepotid() {
        return anotherdepotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withAnotherdepotid(Long anotherdepotid) {
        this.setAnotherdepotid(anotherdepotid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.AnotherDepotId
     *
     * @param anotherdepotid the value for jsh_depotitem.AnotherDepotId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setAnotherdepotid(Long anotherdepotid) {
        this.anotherdepotid = anotherdepotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxRate
     *
     * @return the value of jsh_depotitem.TaxRate
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getTaxrate() {
        return taxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withTaxrate(BigDecimal taxrate) {
        this.setTaxrate(taxrate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxRate
     *
     * @param taxrate the value for jsh_depotitem.TaxRate
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTaxrate(BigDecimal taxrate) {
        this.taxrate = taxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxMoney
     *
     * @return the value of jsh_depotitem.TaxMoney
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getTaxmoney() {
        return taxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withTaxmoney(BigDecimal taxmoney) {
        this.setTaxmoney(taxmoney);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxMoney
     *
     * @param taxmoney the value for jsh_depotitem.TaxMoney
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTaxmoney(BigDecimal taxmoney) {
        this.taxmoney = taxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.TaxLastMoney
     *
     * @return the value of jsh_depotitem.TaxLastMoney
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getTaxlastmoney() {
        return taxlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withTaxlastmoney(BigDecimal taxlastmoney) {
        this.setTaxlastmoney(taxlastmoney);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.TaxLastMoney
     *
     * @param taxlastmoney the value for jsh_depotitem.TaxLastMoney
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTaxlastmoney(BigDecimal taxlastmoney) {
        this.taxlastmoney = taxlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField1
     *
     * @return the value of jsh_depotitem.OtherField1
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield1() {
        return otherfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withOtherfield1(String otherfield1) {
        this.setOtherfield1(otherfield1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField1
     *
     * @param otherfield1 the value for jsh_depotitem.OtherField1
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield1(String otherfield1) {
        this.otherfield1 = otherfield1 == null ? null : otherfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField2
     *
     * @return the value of jsh_depotitem.OtherField2
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield2() {
        return otherfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withOtherfield2(String otherfield2) {
        this.setOtherfield2(otherfield2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField2
     *
     * @param otherfield2 the value for jsh_depotitem.OtherField2
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield2(String otherfield2) {
        this.otherfield2 = otherfield2 == null ? null : otherfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField3
     *
     * @return the value of jsh_depotitem.OtherField3
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield3() {
        return otherfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withOtherfield3(String otherfield3) {
        this.setOtherfield3(otherfield3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField3
     *
     * @param otherfield3 the value for jsh_depotitem.OtherField3
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield3(String otherfield3) {
        this.otherfield3 = otherfield3 == null ? null : otherfield3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField4
     *
     * @return the value of jsh_depotitem.OtherField4
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield4() {
        return otherfield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withOtherfield4(String otherfield4) {
        this.setOtherfield4(otherfield4);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField4
     *
     * @param otherfield4 the value for jsh_depotitem.OtherField4
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield4(String otherfield4) {
        this.otherfield4 = otherfield4 == null ? null : otherfield4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.OtherField5
     *
     * @return the value of jsh_depotitem.OtherField5
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield5() {
        return otherfield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withOtherfield5(String otherfield5) {
        this.setOtherfield5(otherfield5);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.OtherField5
     *
     * @param otherfield5 the value for jsh_depotitem.OtherField5
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield5(String otherfield5) {
        this.otherfield5 = otherfield5 == null ? null : otherfield5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.MType
     *
     * @return the value of jsh_depotitem.MType
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withMtype(String mtype) {
        this.setMtype(mtype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.MType
     *
     * @param mtype the value for jsh_depotitem.MType
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMtype(String mtype) {
        this.mtype = mtype == null ? null : mtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.tenant_id
     *
     * @return the value of jsh_depotitem.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.tenant_id
     *
     * @param tenantId the value for jsh_depotitem.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depotitem.delete_Flag
     *
     * @return the value of jsh_depotitem.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshdepotItem withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depotitem.delete_Flag
     *
     * @param deleteFlag the value for jsh_depotitem.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depotitem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", headerid=").append(headerid);
        sb.append(", materialid=").append(materialid);
        sb.append(", materialExtendId=").append(materialExtendId);
        sb.append(", munit=").append(munit);
        sb.append(", opernumber=").append(opernumber);
        sb.append(", basicnumber=").append(basicnumber);
        sb.append(", unitprice=").append(unitprice);
        sb.append(", taxunitprice=").append(taxunitprice);
        sb.append(", allprice=").append(allprice);
        sb.append(", remark=").append(remark);
        sb.append(", img=").append(img);
        sb.append(", incidentals=").append(incidentals);
        sb.append(", depotid=").append(depotid);
        sb.append(", anotherdepotid=").append(anotherdepotid);
        sb.append(", taxrate=").append(taxrate);
        sb.append(", taxmoney=").append(taxmoney);
        sb.append(", taxlastmoney=").append(taxlastmoney);
        sb.append(", otherfield1=").append(otherfield1);
        sb.append(", otherfield2=").append(otherfield2);
        sb.append(", otherfield3=").append(otherfield3);
        sb.append(", otherfield4=").append(otherfield4);
        sb.append(", otherfield5=").append(otherfield5);
        sb.append(", mtype=").append(mtype);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}