package com.springboot.college.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class JshDepot implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.address
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.warehousing
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal warehousing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.truckage
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal truckage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.principal
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_depot.is_default
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.id
     *
     * @return the value of jsh_depot.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.id
     *
     * @param id the value for jsh_depot.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.name
     *
     * @return the value of jsh_depot.name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.name
     *
     * @param name the value for jsh_depot.name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.address
     *
     * @return the value of jsh_depot.address
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withAddress(String address) {
        this.setAddress(address);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.address
     *
     * @param address the value for jsh_depot.address
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.warehousing
     *
     * @return the value of jsh_depot.warehousing
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getWarehousing() {
        return warehousing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withWarehousing(BigDecimal warehousing) {
        this.setWarehousing(warehousing);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.warehousing
     *
     * @param warehousing the value for jsh_depot.warehousing
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setWarehousing(BigDecimal warehousing) {
        this.warehousing = warehousing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.truckage
     *
     * @return the value of jsh_depot.truckage
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getTruckage() {
        return truckage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withTruckage(BigDecimal truckage) {
        this.setTruckage(truckage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.truckage
     *
     * @param truckage the value for jsh_depot.truckage
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTruckage(BigDecimal truckage) {
        this.truckage = truckage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.type
     *
     * @return the value of jsh_depot.type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withType(Integer type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.type
     *
     * @param type the value for jsh_depot.type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.sort
     *
     * @return the value of jsh_depot.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withSort(String sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.sort
     *
     * @param sort the value for jsh_depot.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.remark
     *
     * @return the value of jsh_depot.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.remark
     *
     * @param remark the value for jsh_depot.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.principal
     *
     * @return the value of jsh_depot.principal
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withPrincipal(Long principal) {
        this.setPrincipal(principal);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.principal
     *
     * @param principal the value for jsh_depot.principal
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPrincipal(Long principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.tenant_id
     *
     * @return the value of jsh_depot.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.tenant_id
     *
     * @param tenantId the value for jsh_depot.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.delete_Flag
     *
     * @return the value of jsh_depot.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.delete_Flag
     *
     * @param deleteFlag the value for jsh_depot.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_depot.is_default
     *
     * @return the value of jsh_depot.is_default
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshDepot withIsDefault(Boolean isDefault) {
        this.setIsDefault(isDefault);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_depot.is_default
     *
     * @param isDefault the value for jsh_depot.is_default
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_depot
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", warehousing=").append(warehousing);
        sb.append(", truckage=").append(truckage);
        sb.append(", type=").append(type);
        sb.append(", sort=").append(sort);
        sb.append(", remark=").append(remark);
        sb.append(", principal=").append(principal);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", isDefault=").append(isDefault);
        sb.append("]");
        return sb.toString();
    }
}