package com.springboot.college.model;

import java.io.Serializable;

public class JshFunctions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.PNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String pnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.URL
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.State
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.PushBtn
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String pushbtn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.icon
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Id
     *
     * @return the value of jsh_functions.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Id
     *
     * @param id the value for jsh_functions.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Number
     *
     * @return the value of jsh_functions.Number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withNumber(String number) {
        this.setNumber(number);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Number
     *
     * @param number the value for jsh_functions.Number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Name
     *
     * @return the value of jsh_functions.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Name
     *
     * @param name the value for jsh_functions.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.PNumber
     *
     * @return the value of jsh_functions.PNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withPnumber(String pnumber) {
        this.setPnumber(pnumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.PNumber
     *
     * @param pnumber the value for jsh_functions.PNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPnumber(String pnumber) {
        this.pnumber = pnumber == null ? null : pnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.URL
     *
     * @return the value of jsh_functions.URL
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.URL
     *
     * @param url the value for jsh_functions.URL
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.State
     *
     * @return the value of jsh_functions.State
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withState(Boolean state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.State
     *
     * @param state the value for jsh_functions.State
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Sort
     *
     * @return the value of jsh_functions.Sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withSort(String sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Sort
     *
     * @param sort the value for jsh_functions.Sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Enabled
     *
     * @return the value of jsh_functions.Enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withEnabled(Boolean enabled) {
        this.setEnabled(enabled);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Enabled
     *
     * @param enabled the value for jsh_functions.Enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Type
     *
     * @return the value of jsh_functions.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Type
     *
     * @param type the value for jsh_functions.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.PushBtn
     *
     * @return the value of jsh_functions.PushBtn
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getPushbtn() {
        return pushbtn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withPushbtn(String pushbtn) {
        this.setPushbtn(pushbtn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.PushBtn
     *
     * @param pushbtn the value for jsh_functions.PushBtn
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPushbtn(String pushbtn) {
        this.pushbtn = pushbtn == null ? null : pushbtn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.icon
     *
     * @return the value of jsh_functions.icon
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withIcon(String icon) {
        this.setIcon(icon);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.icon
     *
     * @param icon the value for jsh_functions.icon
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.delete_Flag
     *
     * @return the value of jsh_functions.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshFunctions withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.delete_Flag
     *
     * @param deleteFlag the value for jsh_functions.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_functions
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", number=").append(number);
        sb.append(", name=").append(name);
        sb.append(", pnumber=").append(pnumber);
        sb.append(", url=").append(url);
        sb.append(", state=").append(state);
        sb.append(", sort=").append(sort);
        sb.append(", enabled=").append(enabled);
        sb.append(", type=").append(type);
        sb.append(", pushbtn=").append(pushbtn);
        sb.append(", icon=").append(icon);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}