package com.springboot.college.model;

import java.io.Serializable;

public class JshMaterialProperty implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialproperty.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialproperty.nativeName
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String nativename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialproperty.enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialproperty.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialproperty.anotherName
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String anothername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialproperty.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialproperty.id
     *
     * @return the value of jsh_materialproperty.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialProperty withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialproperty.id
     *
     * @param id the value for jsh_materialproperty.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialproperty.nativeName
     *
     * @return the value of jsh_materialproperty.nativeName
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getNativename() {
        return nativename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialProperty withNativename(String nativename) {
        this.setNativename(nativename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialproperty.nativeName
     *
     * @param nativename the value for jsh_materialproperty.nativeName
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setNativename(String nativename) {
        this.nativename = nativename == null ? null : nativename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialproperty.enabled
     *
     * @return the value of jsh_materialproperty.enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialProperty withEnabled(Boolean enabled) {
        this.setEnabled(enabled);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialproperty.enabled
     *
     * @param enabled the value for jsh_materialproperty.enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialproperty.sort
     *
     * @return the value of jsh_materialproperty.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialProperty withSort(String sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialproperty.sort
     *
     * @param sort the value for jsh_materialproperty.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialproperty.anotherName
     *
     * @return the value of jsh_materialproperty.anotherName
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getAnothername() {
        return anothername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialProperty withAnothername(String anothername) {
        this.setAnothername(anothername);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialproperty.anotherName
     *
     * @param anothername the value for jsh_materialproperty.anotherName
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setAnothername(String anothername) {
        this.anothername = anothername == null ? null : anothername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialproperty.delete_Flag
     *
     * @return the value of jsh_materialproperty.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialProperty withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialproperty.delete_Flag
     *
     * @param deleteFlag the value for jsh_materialproperty.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialproperty
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", nativename=").append(nativename);
        sb.append(", enabled=").append(enabled);
        sb.append(", sort=").append(sort);
        sb.append(", anothername=").append(anothername);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}