package com.springboot.college.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class JshMaterial implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.CategoryId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Mfrs
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String mfrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Packing
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal packing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.SafetyStock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal safetystock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Model
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Standard
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Color
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.RetailPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal retailprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.LowPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal lowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.PresetPriceOne
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal presetpriceone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.PresetPriceTwo
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private BigDecimal presetpricetwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.UnitId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long unitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.FirstOutUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String firstoutunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.FirstInUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String firstinunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.PriceStrategy
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String pricestrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.Enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.OtherField1
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.OtherField2
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.OtherField3
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String otherfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.enableSerialNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String enableserialnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_material.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Id
     *
     * @return the value of jsh_material.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Id
     *
     * @param id the value for jsh_material.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.CategoryId
     *
     * @return the value of jsh_material.CategoryId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withCategoryid(Long categoryid) {
        this.setCategoryid(categoryid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.CategoryId
     *
     * @param categoryid the value for jsh_material.CategoryId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Name
     *
     * @return the value of jsh_material.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Name
     *
     * @param name the value for jsh_material.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Mfrs
     *
     * @return the value of jsh_material.Mfrs
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getMfrs() {
        return mfrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withMfrs(String mfrs) {
        this.setMfrs(mfrs);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Mfrs
     *
     * @param mfrs the value for jsh_material.Mfrs
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMfrs(String mfrs) {
        this.mfrs = mfrs == null ? null : mfrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Packing
     *
     * @return the value of jsh_material.Packing
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getPacking() {
        return packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withPacking(BigDecimal packing) {
        this.setPacking(packing);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Packing
     *
     * @param packing the value for jsh_material.Packing
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPacking(BigDecimal packing) {
        this.packing = packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.SafetyStock
     *
     * @return the value of jsh_material.SafetyStock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getSafetystock() {
        return safetystock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withSafetystock(BigDecimal safetystock) {
        this.setSafetystock(safetystock);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.SafetyStock
     *
     * @param safetystock the value for jsh_material.SafetyStock
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSafetystock(BigDecimal safetystock) {
        this.safetystock = safetystock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Model
     *
     * @return the value of jsh_material.Model
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withModel(String model) {
        this.setModel(model);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Model
     *
     * @param model the value for jsh_material.Model
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Standard
     *
     * @return the value of jsh_material.Standard
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withStandard(String standard) {
        this.setStandard(standard);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Standard
     *
     * @param standard the value for jsh_material.Standard
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Color
     *
     * @return the value of jsh_material.Color
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withColor(String color) {
        this.setColor(color);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Color
     *
     * @param color the value for jsh_material.Color
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Unit
     *
     * @return the value of jsh_material.Unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withUnit(String unit) {
        this.setUnit(unit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Unit
     *
     * @param unit the value for jsh_material.Unit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Remark
     *
     * @return the value of jsh_material.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Remark
     *
     * @param remark the value for jsh_material.Remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.RetailPrice
     *
     * @return the value of jsh_material.RetailPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getRetailprice() {
        return retailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withRetailprice(BigDecimal retailprice) {
        this.setRetailprice(retailprice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.RetailPrice
     *
     * @param retailprice the value for jsh_material.RetailPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRetailprice(BigDecimal retailprice) {
        this.retailprice = retailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.LowPrice
     *
     * @return the value of jsh_material.LowPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getLowprice() {
        return lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withLowprice(BigDecimal lowprice) {
        this.setLowprice(lowprice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.LowPrice
     *
     * @param lowprice the value for jsh_material.LowPrice
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setLowprice(BigDecimal lowprice) {
        this.lowprice = lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.PresetPriceOne
     *
     * @return the value of jsh_material.PresetPriceOne
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getPresetpriceone() {
        return presetpriceone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withPresetpriceone(BigDecimal presetpriceone) {
        this.setPresetpriceone(presetpriceone);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.PresetPriceOne
     *
     * @param presetpriceone the value for jsh_material.PresetPriceOne
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPresetpriceone(BigDecimal presetpriceone) {
        this.presetpriceone = presetpriceone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.PresetPriceTwo
     *
     * @return the value of jsh_material.PresetPriceTwo
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public BigDecimal getPresetpricetwo() {
        return presetpricetwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withPresetpricetwo(BigDecimal presetpricetwo) {
        this.setPresetpricetwo(presetpricetwo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.PresetPriceTwo
     *
     * @param presetpricetwo the value for jsh_material.PresetPriceTwo
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPresetpricetwo(BigDecimal presetpricetwo) {
        this.presetpricetwo = presetpricetwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.UnitId
     *
     * @return the value of jsh_material.UnitId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withUnitid(Long unitid) {
        this.setUnitid(unitid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.UnitId
     *
     * @param unitid the value for jsh_material.UnitId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUnitid(Long unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.FirstOutUnit
     *
     * @return the value of jsh_material.FirstOutUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getFirstoutunit() {
        return firstoutunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withFirstoutunit(String firstoutunit) {
        this.setFirstoutunit(firstoutunit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.FirstOutUnit
     *
     * @param firstoutunit the value for jsh_material.FirstOutUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setFirstoutunit(String firstoutunit) {
        this.firstoutunit = firstoutunit == null ? null : firstoutunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.FirstInUnit
     *
     * @return the value of jsh_material.FirstInUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getFirstinunit() {
        return firstinunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withFirstinunit(String firstinunit) {
        this.setFirstinunit(firstinunit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.FirstInUnit
     *
     * @param firstinunit the value for jsh_material.FirstInUnit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setFirstinunit(String firstinunit) {
        this.firstinunit = firstinunit == null ? null : firstinunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.PriceStrategy
     *
     * @return the value of jsh_material.PriceStrategy
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getPricestrategy() {
        return pricestrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withPricestrategy(String pricestrategy) {
        this.setPricestrategy(pricestrategy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.PriceStrategy
     *
     * @param pricestrategy the value for jsh_material.PriceStrategy
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPricestrategy(String pricestrategy) {
        this.pricestrategy = pricestrategy == null ? null : pricestrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.Enabled
     *
     * @return the value of jsh_material.Enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withEnabled(Boolean enabled) {
        this.setEnabled(enabled);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.Enabled
     *
     * @param enabled the value for jsh_material.Enabled
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.OtherField1
     *
     * @return the value of jsh_material.OtherField1
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield1() {
        return otherfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withOtherfield1(String otherfield1) {
        this.setOtherfield1(otherfield1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.OtherField1
     *
     * @param otherfield1 the value for jsh_material.OtherField1
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield1(String otherfield1) {
        this.otherfield1 = otherfield1 == null ? null : otherfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.OtherField2
     *
     * @return the value of jsh_material.OtherField2
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield2() {
        return otherfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withOtherfield2(String otherfield2) {
        this.setOtherfield2(otherfield2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.OtherField2
     *
     * @param otherfield2 the value for jsh_material.OtherField2
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield2(String otherfield2) {
        this.otherfield2 = otherfield2 == null ? null : otherfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.OtherField3
     *
     * @return the value of jsh_material.OtherField3
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getOtherfield3() {
        return otherfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withOtherfield3(String otherfield3) {
        this.setOtherfield3(otherfield3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.OtherField3
     *
     * @param otherfield3 the value for jsh_material.OtherField3
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOtherfield3(String otherfield3) {
        this.otherfield3 = otherfield3 == null ? null : otherfield3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.enableSerialNumber
     *
     * @return the value of jsh_material.enableSerialNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getEnableserialnumber() {
        return enableserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withEnableserialnumber(String enableserialnumber) {
        this.setEnableserialnumber(enableserialnumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.enableSerialNumber
     *
     * @param enableserialnumber the value for jsh_material.enableSerialNumber
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setEnableserialnumber(String enableserialnumber) {
        this.enableserialnumber = enableserialnumber == null ? null : enableserialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.tenant_id
     *
     * @return the value of jsh_material.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.tenant_id
     *
     * @param tenantId the value for jsh_material.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_material.delete_Flag
     *
     * @return the value of jsh_material.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterial withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_material.delete_Flag
     *
     * @param deleteFlag the value for jsh_material.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_material
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", categoryid=").append(categoryid);
        sb.append(", name=").append(name);
        sb.append(", mfrs=").append(mfrs);
        sb.append(", packing=").append(packing);
        sb.append(", safetystock=").append(safetystock);
        sb.append(", model=").append(model);
        sb.append(", standard=").append(standard);
        sb.append(", color=").append(color);
        sb.append(", unit=").append(unit);
        sb.append(", remark=").append(remark);
        sb.append(", retailprice=").append(retailprice);
        sb.append(", lowprice=").append(lowprice);
        sb.append(", presetpriceone=").append(presetpriceone);
        sb.append(", presetpricetwo=").append(presetpricetwo);
        sb.append(", unitid=").append(unitid);
        sb.append(", firstoutunit=").append(firstoutunit);
        sb.append(", firstinunit=").append(firstinunit);
        sb.append(", pricestrategy=").append(pricestrategy);
        sb.append(", enabled=").append(enabled);
        sb.append(", otherfield1=").append(otherfield1);
        sb.append(", otherfield2=").append(otherfield2);
        sb.append(", otherfield3=").append(otherfield3);
        sb.append(", enableserialnumber=").append(enableserialnumber);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}