package com.springboot.college.model;

import java.io.Serializable;
import java.util.Date;

public class JshMaterialCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.CategoryLevel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Short categorylevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.ParentId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.serial_no
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.update_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.Id
     *
     * @return the value of jsh_materialcategory.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.Id
     *
     * @param id the value for jsh_materialcategory.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.Name
     *
     * @return the value of jsh_materialcategory.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.Name
     *
     * @param name the value for jsh_materialcategory.Name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.CategoryLevel
     *
     * @return the value of jsh_materialcategory.CategoryLevel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Short getCategorylevel() {
        return categorylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withCategorylevel(Short categorylevel) {
        this.setCategorylevel(categorylevel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.CategoryLevel
     *
     * @param categorylevel the value for jsh_materialcategory.CategoryLevel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCategorylevel(Short categorylevel) {
        this.categorylevel = categorylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.ParentId
     *
     * @return the value of jsh_materialcategory.ParentId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withParentid(Long parentid) {
        this.setParentid(parentid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.ParentId
     *
     * @param parentid the value for jsh_materialcategory.ParentId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.sort
     *
     * @return the value of jsh_materialcategory.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withSort(String sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.sort
     *
     * @param sort the value for jsh_materialcategory.sort
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.status
     *
     * @return the value of jsh_materialcategory.status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withStatus(String status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.status
     *
     * @param status the value for jsh_materialcategory.status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.serial_no
     *
     * @return the value of jsh_materialcategory.serial_no
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withSerialNo(String serialNo) {
        this.setSerialNo(serialNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.serial_no
     *
     * @param serialNo the value for jsh_materialcategory.serial_no
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.remark
     *
     * @return the value of jsh_materialcategory.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.remark
     *
     * @param remark the value for jsh_materialcategory.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.create_time
     *
     * @return the value of jsh_materialcategory.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.create_time
     *
     * @param createTime the value for jsh_materialcategory.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.creator
     *
     * @return the value of jsh_materialcategory.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withCreator(Long creator) {
        this.setCreator(creator);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.creator
     *
     * @param creator the value for jsh_materialcategory.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.update_time
     *
     * @return the value of jsh_materialcategory.update_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.update_time
     *
     * @param updateTime the value for jsh_materialcategory.update_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.updater
     *
     * @return the value of jsh_materialcategory.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withUpdater(Long updater) {
        this.setUpdater(updater);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.updater
     *
     * @param updater the value for jsh_materialcategory.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.tenant_id
     *
     * @return the value of jsh_materialcategory.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMaterialCategory withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.tenant_id
     *
     * @param tenantId the value for jsh_materialcategory.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_materialcategory
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", categorylevel=").append(categorylevel);
        sb.append(", parentid=").append(parentid);
        sb.append(", sort=").append(sort);
        sb.append(", status=").append(status);
        sb.append(", serialNo=").append(serialNo);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", creator=").append(creator);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updater=").append(updater);
        sb.append(", tenantId=").append(tenantId);
        sb.append("]");
        return sb.toString();
    }
}