package com.springboot.college.model;

import java.io.Serializable;
import java.util.Date;

public class JshMsg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.msg_title
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String msgTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.msg_content
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_msg.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.id
     *
     * @return the value of jsh_msg.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.id
     *
     * @param id the value for jsh_msg.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.msg_title
     *
     * @return the value of jsh_msg.msg_title
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withMsgTitle(String msgTitle) {
        this.setMsgTitle(msgTitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.msg_title
     *
     * @param msgTitle the value for jsh_msg.msg_title
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle == null ? null : msgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.msg_content
     *
     * @return the value of jsh_msg.msg_content
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withMsgContent(String msgContent) {
        this.setMsgContent(msgContent);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.msg_content
     *
     * @param msgContent the value for jsh_msg.msg_content
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.create_time
     *
     * @return the value of jsh_msg.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.create_time
     *
     * @param createTime the value for jsh_msg.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.type
     *
     * @return the value of jsh_msg.type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.type
     *
     * @param type the value for jsh_msg.type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.status
     *
     * @return the value of jsh_msg.status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withStatus(String status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.status
     *
     * @param status the value for jsh_msg.status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.tenant_id
     *
     * @return the value of jsh_msg.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.tenant_id
     *
     * @param tenantId the value for jsh_msg.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_msg.delete_Flag
     *
     * @return the value of jsh_msg.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshMsg withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_msg.delete_Flag
     *
     * @param deleteFlag the value for jsh_msg.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_msg
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", msgTitle=").append(msgTitle);
        sb.append(", msgContent=").append(msgContent);
        sb.append(", createTime=").append(createTime);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}