package com.springboot.college.model;

import java.io.Serializable;
import java.util.Date;

public class JshOrgaUserRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.orga_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long orgaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.user_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.user_blng_orga_dspl_seq
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String userBlngOrgaDsplSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.delete_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.update_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.id
     *
     * @return the value of jsh_orga_user_rel.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.id
     *
     * @param id the value for jsh_orga_user_rel.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.orga_id
     *
     * @return the value of jsh_orga_user_rel.orga_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getOrgaId() {
        return orgaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withOrgaId(Long orgaId) {
        this.setOrgaId(orgaId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.orga_id
     *
     * @param orgaId the value for jsh_orga_user_rel.orga_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setOrgaId(Long orgaId) {
        this.orgaId = orgaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.user_id
     *
     * @return the value of jsh_orga_user_rel.user_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.user_id
     *
     * @param userId the value for jsh_orga_user_rel.user_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.user_blng_orga_dspl_seq
     *
     * @return the value of jsh_orga_user_rel.user_blng_orga_dspl_seq
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getUserBlngOrgaDsplSeq() {
        return userBlngOrgaDsplSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withUserBlngOrgaDsplSeq(String userBlngOrgaDsplSeq) {
        this.setUserBlngOrgaDsplSeq(userBlngOrgaDsplSeq);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.user_blng_orga_dspl_seq
     *
     * @param userBlngOrgaDsplSeq the value for jsh_orga_user_rel.user_blng_orga_dspl_seq
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUserBlngOrgaDsplSeq(String userBlngOrgaDsplSeq) {
        this.userBlngOrgaDsplSeq = userBlngOrgaDsplSeq == null ? null : userBlngOrgaDsplSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.delete_flag
     *
     * @return the value of jsh_orga_user_rel.delete_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.delete_flag
     *
     * @param deleteFlag the value for jsh_orga_user_rel.delete_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.create_time
     *
     * @return the value of jsh_orga_user_rel.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.create_time
     *
     * @param createTime the value for jsh_orga_user_rel.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.creator
     *
     * @return the value of jsh_orga_user_rel.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withCreator(Long creator) {
        this.setCreator(creator);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.creator
     *
     * @param creator the value for jsh_orga_user_rel.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.update_time
     *
     * @return the value of jsh_orga_user_rel.update_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.update_time
     *
     * @param updateTime the value for jsh_orga_user_rel.update_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.updater
     *
     * @return the value of jsh_orga_user_rel.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withUpdater(Long updater) {
        this.setUpdater(updater);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.updater
     *
     * @param updater the value for jsh_orga_user_rel.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_orga_user_rel.tenant_id
     *
     * @return the value of jsh_orga_user_rel.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshOrgaUserRel withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_orga_user_rel.tenant_id
     *
     * @param tenantId the value for jsh_orga_user_rel.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_orga_user_rel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgaId=").append(orgaId);
        sb.append(", userId=").append(userId);
        sb.append(", userBlngOrgaDsplSeq=").append(userBlngOrgaDsplSeq);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", creator=").append(creator);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updater=").append(updater);
        sb.append(", tenantId=").append(tenantId);
        sb.append("]");
        return sb.toString();
    }
}