package com.springboot.college.model;

import java.io.Serializable;
import java.util.Date;

public class JshSerialNumber implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.material_Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.serial_Number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.is_Sell
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String isSell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.create_Time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.update_Time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.depothead_Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long depotheadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_serial_number.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.id
     *
     * @return the value of jsh_serial_number.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.id
     *
     * @param id the value for jsh_serial_number.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.material_Id
     *
     * @return the value of jsh_serial_number.material_Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withMaterialId(Long materialId) {
        this.setMaterialId(materialId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.material_Id
     *
     * @param materialId the value for jsh_serial_number.material_Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMaterialId(Long materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.serial_Number
     *
     * @return the value of jsh_serial_number.serial_Number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withSerialNumber(String serialNumber) {
        this.setSerialNumber(serialNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.serial_Number
     *
     * @param serialNumber the value for jsh_serial_number.serial_Number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.is_Sell
     *
     * @return the value of jsh_serial_number.is_Sell
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getIsSell() {
        return isSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withIsSell(String isSell) {
        this.setIsSell(isSell);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.is_Sell
     *
     * @param isSell the value for jsh_serial_number.is_Sell
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIsSell(String isSell) {
        this.isSell = isSell == null ? null : isSell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.remark
     *
     * @return the value of jsh_serial_number.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.remark
     *
     * @param remark the value for jsh_serial_number.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.delete_Flag
     *
     * @return the value of jsh_serial_number.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.delete_Flag
     *
     * @param deleteFlag the value for jsh_serial_number.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.create_Time
     *
     * @return the value of jsh_serial_number.create_Time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.create_Time
     *
     * @param createTime the value for jsh_serial_number.create_Time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.creator
     *
     * @return the value of jsh_serial_number.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withCreator(Long creator) {
        this.setCreator(creator);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.creator
     *
     * @param creator the value for jsh_serial_number.creator
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.update_Time
     *
     * @return the value of jsh_serial_number.update_Time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.update_Time
     *
     * @param updateTime the value for jsh_serial_number.update_Time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.updater
     *
     * @return the value of jsh_serial_number.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withUpdater(Long updater) {
        this.setUpdater(updater);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.updater
     *
     * @param updater the value for jsh_serial_number.updater
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.depothead_Id
     *
     * @return the value of jsh_serial_number.depothead_Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getDepotheadId() {
        return depotheadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withDepotheadId(Long depotheadId) {
        this.setDepotheadId(depotheadId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.depothead_Id
     *
     * @param depotheadId the value for jsh_serial_number.depothead_Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDepotheadId(Long depotheadId) {
        this.depotheadId = depotheadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_serial_number.tenant_id
     *
     * @return the value of jsh_serial_number.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSerialNumber withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_serial_number.tenant_id
     *
     * @param tenantId the value for jsh_serial_number.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_serial_number
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", materialId=").append(materialId);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", isSell=").append(isSell);
        sb.append(", remark=").append(remark);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", creator=").append(creator);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updater=").append(updater);
        sb.append(", depotheadId=").append(depotheadId);
        sb.append(", tenantId=").append(tenantId);
        sb.append("]");
        return sb.toString();
    }
}