package com.springboot.college.model;

import java.io.Serializable;

public class JshSequence implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_sequence.seq_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String seqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_sequence.min_value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long minValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_sequence.max_value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_sequence.current_val
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long currentVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_sequence.increment_val
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Integer incrementVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_sequence.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_sequence.seq_name
     *
     * @return the value of jsh_sequence.seq_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSequence withSeqName(String seqName) {
        this.setSeqName(seqName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_sequence.seq_name
     *
     * @param seqName the value for jsh_sequence.seq_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName == null ? null : seqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_sequence.min_value
     *
     * @return the value of jsh_sequence.min_value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSequence withMinValue(Long minValue) {
        this.setMinValue(minValue);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_sequence.min_value
     *
     * @param minValue the value for jsh_sequence.min_value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMinValue(Long minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_sequence.max_value
     *
     * @return the value of jsh_sequence.max_value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSequence withMaxValue(Long maxValue) {
        this.setMaxValue(maxValue);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_sequence.max_value
     *
     * @param maxValue the value for jsh_sequence.max_value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setMaxValue(Long maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_sequence.current_val
     *
     * @return the value of jsh_sequence.current_val
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSequence withCurrentVal(Long currentVal) {
        this.setCurrentVal(currentVal);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_sequence.current_val
     *
     * @param currentVal the value for jsh_sequence.current_val
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCurrentVal(Long currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_sequence.increment_val
     *
     * @return the value of jsh_sequence.increment_val
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Integer getIncrementVal() {
        return incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSequence withIncrementVal(Integer incrementVal) {
        this.setIncrementVal(incrementVal);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_sequence.increment_val
     *
     * @param incrementVal the value for jsh_sequence.increment_val
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIncrementVal(Integer incrementVal) {
        this.incrementVal = incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_sequence.remark
     *
     * @return the value of jsh_sequence.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSequence withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_sequence.remark
     *
     * @param remark the value for jsh_sequence.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_sequence
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqName=").append(seqName);
        sb.append(", minValue=").append(minValue);
        sb.append(", maxValue=").append(maxValue);
        sb.append(", currentVal=").append(currentVal);
        sb.append(", incrementVal=").append(incrementVal);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}