package com.springboot.college.model;

import java.io.Serializable;

public class JshSystemConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_contacts
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String companyContacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_address
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_tel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String companyTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_fax
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String companyFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_post_code
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String companyPostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.depot_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String depotFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.customer_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String customerFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.id
     *
     * @return the value of jsh_systemconfig.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.id
     *
     * @param id the value for jsh_systemconfig.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_name
     *
     * @return the value of jsh_systemconfig.company_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCompanyName(String companyName) {
        this.setCompanyName(companyName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_name
     *
     * @param companyName the value for jsh_systemconfig.company_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_contacts
     *
     * @return the value of jsh_systemconfig.company_contacts
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCompanyContacts() {
        return companyContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCompanyContacts(String companyContacts) {
        this.setCompanyContacts(companyContacts);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_contacts
     *
     * @param companyContacts the value for jsh_systemconfig.company_contacts
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCompanyContacts(String companyContacts) {
        this.companyContacts = companyContacts == null ? null : companyContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_address
     *
     * @return the value of jsh_systemconfig.company_address
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCompanyAddress(String companyAddress) {
        this.setCompanyAddress(companyAddress);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_address
     *
     * @param companyAddress the value for jsh_systemconfig.company_address
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_tel
     *
     * @return the value of jsh_systemconfig.company_tel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCompanyTel(String companyTel) {
        this.setCompanyTel(companyTel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_tel
     *
     * @param companyTel the value for jsh_systemconfig.company_tel
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel == null ? null : companyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_fax
     *
     * @return the value of jsh_systemconfig.company_fax
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCompanyFax() {
        return companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCompanyFax(String companyFax) {
        this.setCompanyFax(companyFax);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_fax
     *
     * @param companyFax the value for jsh_systemconfig.company_fax
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCompanyFax(String companyFax) {
        this.companyFax = companyFax == null ? null : companyFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_post_code
     *
     * @return the value of jsh_systemconfig.company_post_code
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCompanyPostCode() {
        return companyPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCompanyPostCode(String companyPostCode) {
        this.setCompanyPostCode(companyPostCode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_post_code
     *
     * @param companyPostCode the value for jsh_systemconfig.company_post_code
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCompanyPostCode(String companyPostCode) {
        this.companyPostCode = companyPostCode == null ? null : companyPostCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.depot_flag
     *
     * @return the value of jsh_systemconfig.depot_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDepotFlag() {
        return depotFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withDepotFlag(String depotFlag) {
        this.setDepotFlag(depotFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.depot_flag
     *
     * @param depotFlag the value for jsh_systemconfig.depot_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDepotFlag(String depotFlag) {
        this.depotFlag = depotFlag == null ? null : depotFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.customer_flag
     *
     * @return the value of jsh_systemconfig.customer_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getCustomerFlag() {
        return customerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withCustomerFlag(String customerFlag) {
        this.setCustomerFlag(customerFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.customer_flag
     *
     * @param customerFlag the value for jsh_systemconfig.customer_flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCustomerFlag(String customerFlag) {
        this.customerFlag = customerFlag == null ? null : customerFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.tenant_id
     *
     * @return the value of jsh_systemconfig.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.tenant_id
     *
     * @param tenantId the value for jsh_systemconfig.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.delete_Flag
     *
     * @return the value of jsh_systemconfig.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshSystemConfig withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.delete_Flag
     *
     * @param deleteFlag the value for jsh_systemconfig.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_systemconfig
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyName=").append(companyName);
        sb.append(", companyContacts=").append(companyContacts);
        sb.append(", companyAddress=").append(companyAddress);
        sb.append(", companyTel=").append(companyTel);
        sb.append(", companyFax=").append(companyFax);
        sb.append(", companyPostCode=").append(companyPostCode);
        sb.append(", depotFlag=").append(depotFlag);
        sb.append(", customerFlag=").append(customerFlag);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}