package com.springboot.college.model;

import java.io.Serializable;
import java.util.Date;

public class JshTenant implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_tenant.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_tenant.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_tenant.login_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_tenant.user_num_limit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Integer userNumLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_tenant.bills_num_limit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Integer billsNumLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_tenant.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_tenant.id
     *
     * @return the value of jsh_tenant.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshTenant withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_tenant.id
     *
     * @param id the value for jsh_tenant.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_tenant.tenant_id
     *
     * @return the value of jsh_tenant.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshTenant withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_tenant.tenant_id
     *
     * @param tenantId the value for jsh_tenant.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_tenant.login_name
     *
     * @return the value of jsh_tenant.login_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshTenant withLoginName(String loginName) {
        this.setLoginName(loginName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_tenant.login_name
     *
     * @param loginName the value for jsh_tenant.login_name
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_tenant.user_num_limit
     *
     * @return the value of jsh_tenant.user_num_limit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Integer getUserNumLimit() {
        return userNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshTenant withUserNumLimit(Integer userNumLimit) {
        this.setUserNumLimit(userNumLimit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_tenant.user_num_limit
     *
     * @param userNumLimit the value for jsh_tenant.user_num_limit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUserNumLimit(Integer userNumLimit) {
        this.userNumLimit = userNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_tenant.bills_num_limit
     *
     * @return the value of jsh_tenant.bills_num_limit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Integer getBillsNumLimit() {
        return billsNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshTenant withBillsNumLimit(Integer billsNumLimit) {
        this.setBillsNumLimit(billsNumLimit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_tenant.bills_num_limit
     *
     * @param billsNumLimit the value for jsh_tenant.bills_num_limit
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setBillsNumLimit(Integer billsNumLimit) {
        this.billsNumLimit = billsNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_tenant.create_time
     *
     * @return the value of jsh_tenant.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshTenant withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_tenant.create_time
     *
     * @param createTime the value for jsh_tenant.create_time
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_tenant
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", loginName=").append(loginName);
        sb.append(", userNumLimit=").append(userNumLimit);
        sb.append(", billsNumLimit=").append(billsNumLimit);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}