package com.springboot.college.model;

import java.io.Serializable;

public class JshUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.username
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.loginame
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String loginame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.password
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.position
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.department
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.email
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.phonenum
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.ismanager
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Byte ismanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.isystem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Byte isystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.Status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.description
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_user.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.id
     *
     * @return the value of jsh_user.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.id
     *
     * @param id the value for jsh_user.id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.username
     *
     * @return the value of jsh_user.username
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.username
     *
     * @param username the value for jsh_user.username
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.loginame
     *
     * @return the value of jsh_user.loginame
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getLoginame() {
        return loginame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withLoginame(String loginame) {
        this.setLoginame(loginame);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.loginame
     *
     * @param loginame the value for jsh_user.loginame
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setLoginame(String loginame) {
        this.loginame = loginame == null ? null : loginame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.password
     *
     * @return the value of jsh_user.password
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.password
     *
     * @param password the value for jsh_user.password
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.position
     *
     * @return the value of jsh_user.position
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withPosition(String position) {
        this.setPosition(position);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.position
     *
     * @param position the value for jsh_user.position
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.department
     *
     * @return the value of jsh_user.department
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withDepartment(String department) {
        this.setDepartment(department);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.department
     *
     * @param department the value for jsh_user.department
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.email
     *
     * @return the value of jsh_user.email
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withEmail(String email) {
        this.setEmail(email);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.email
     *
     * @param email the value for jsh_user.email
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.phonenum
     *
     * @return the value of jsh_user.phonenum
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withPhonenum(String phonenum) {
        this.setPhonenum(phonenum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.phonenum
     *
     * @param phonenum the value for jsh_user.phonenum
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.ismanager
     *
     * @return the value of jsh_user.ismanager
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Byte getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withIsmanager(Byte ismanager) {
        this.setIsmanager(ismanager);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.ismanager
     *
     * @param ismanager the value for jsh_user.ismanager
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIsmanager(Byte ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.isystem
     *
     * @return the value of jsh_user.isystem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Byte getIsystem() {
        return isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withIsystem(Byte isystem) {
        this.setIsystem(isystem);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.isystem
     *
     * @param isystem the value for jsh_user.isystem
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setIsystem(Byte isystem) {
        this.isystem = isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.Status
     *
     * @return the value of jsh_user.Status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.Status
     *
     * @param status the value for jsh_user.Status
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.description
     *
     * @return the value of jsh_user.description
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.description
     *
     * @param description the value for jsh_user.description
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.remark
     *
     * @return the value of jsh_user.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.remark
     *
     * @param remark the value for jsh_user.remark
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_user.tenant_id
     *
     * @return the value of jsh_user.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUser withTenantId(Long tenantId) {
        this.setTenantId(tenantId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_user.tenant_id
     *
     * @param tenantId the value for jsh_user.tenant_id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_user
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", loginame=").append(loginame);
        sb.append(", password=").append(password);
        sb.append(", position=").append(position);
        sb.append(", department=").append(department);
        sb.append(", email=").append(email);
        sb.append(", phonenum=").append(phonenum);
        sb.append(", ismanager=").append(ismanager);
        sb.append(", isystem=").append(isystem);
        sb.append(", status=").append(status);
        sb.append(", description=").append(description);
        sb.append(", remark=").append(remark);
        sb.append(", tenantId=").append(tenantId);
        sb.append("]");
        return sb.toString();
    }
}