package com.springboot.college.model;

import java.io.Serializable;

public class JshUserBusiness implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_userbusiness.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_userbusiness.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_userbusiness.KeyId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String keyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_userbusiness.Value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_userbusiness.BtnStr
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String btnstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_userbusiness.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_userbusiness.Id
     *
     * @return the value of jsh_userbusiness.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUserBusiness withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_userbusiness.Id
     *
     * @param id the value for jsh_userbusiness.Id
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_userbusiness.Type
     *
     * @return the value of jsh_userbusiness.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUserBusiness withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_userbusiness.Type
     *
     * @param type the value for jsh_userbusiness.Type
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_userbusiness.KeyId
     *
     * @return the value of jsh_userbusiness.KeyId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUserBusiness withKeyid(String keyid) {
        this.setKeyid(keyid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_userbusiness.KeyId
     *
     * @param keyid the value for jsh_userbusiness.KeyId
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setKeyid(String keyid) {
        this.keyid = keyid == null ? null : keyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_userbusiness.Value
     *
     * @return the value of jsh_userbusiness.Value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUserBusiness withValue(String value) {
        this.setValue(value);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_userbusiness.Value
     *
     * @param value the value for jsh_userbusiness.Value
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_userbusiness.BtnStr
     *
     * @return the value of jsh_userbusiness.BtnStr
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getBtnstr() {
        return btnstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUserBusiness withBtnstr(String btnstr) {
        this.setBtnstr(btnstr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_userbusiness.BtnStr
     *
     * @param btnstr the value for jsh_userbusiness.BtnStr
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setBtnstr(String btnstr) {
        this.btnstr = btnstr == null ? null : btnstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_userbusiness.delete_Flag
     *
     * @return the value of jsh_userbusiness.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public JshUserBusiness withDeleteFlag(String deleteFlag) {
        this.setDeleteFlag(deleteFlag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_userbusiness.delete_Flag
     *
     * @param deleteFlag the value for jsh_userbusiness.delete_Flag
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_userbusiness
     *
     * @mbg.generated Wed Mar 25 14:58:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", keyid=").append(keyid);
        sb.append(", value=").append(value);
        sb.append(", btnstr=").append(btnstr);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }
}